### ISSUE TITLE
Hi! I have some problem to ask you! [Code Ask]

### ISSUE THREAD

**Issue by r8pto** [kushagra19/Map_Matching#1]
Dear authors:
Hi, I downloaded your code and has some question about this code. 

1. your code use "pickle.load" to load data, but I don't find this file in your github. Should I create the data by myself?
2.  can you provide a version to directly run? 

Thank you for your work! looking forward your reply!
Darcy

**Comment by kushagra19** [comment]
Hi, I am not the author for that paper, its just my version of implementation of the paper because I could not find the authors variation of implementation. Also, I have added folder saved_dicts which has a sample adjacency list for you to try. Moreover, please uncomment block 40 in ipynb if you want to run the code, as you would have to calculate route distances. And, if you want to visualize the coordinates use the saved csv file in https://kepler.gl/, as kepler has issues rendering in jupyter notebook. If you face any other difficulties, I would be happy to help and soon I also plan to add a proper documentation for the code. Thanks for pointing missing data.

**Comment by r8pto** [comment]
Thank you for your reply! I will try it!
