### ISSUE TITLE
Hi! I have a new question about your data which loaded by pikle.load

### ISSUE THREAD

**Issue by r8pto** [kushagra19/Map_Matching#2]
Hi! Dear friends! I've also been trying to reproduce the results of that paper recently. And I have a new problem about your data. H**ow do you convert the raw data (.xlsx) into a data format that can be used with pickle.load**, that's a piece I'm not particularly familiar with and haven't found any more clues in your code.

**Comment by kushagra19** [comment]
Hi, I assume you download data from https://www.microsoft.com/en-us/research/publication/hidden-markov-map-matching-noise-sparseness/, if yes then I downloaded the text file, converted the text file into numpy data format. Once you have this, you can see in pre_process.py file how the preprocessing is done for the dataset (you can also adjust the part of the map and sampling by adjusting lines 80-83) to convert into adjoint list format which exists in saved_dicts. Also, i did not use the road network given in this link https://www.microsoft.com/en-us/research/publication/hidden-markov-map-matching-noise-sparseness/ because osmnx library for python has already saved road networks for most major cities in the world. So, if you intend to use something other than osmnx, then you will have to adjust the code a bit.

**Comment by r8pto** [comment]
Yes, I downloaded the data from the website. Thank your very much! I get a lot help from here.

**Comment by r8pto** [comment]
Aha, I ran the "Pre-processing" code and find it will take a lot time. Maybe I should find another menthods to deal with the problem.

**Comment by kushagra19** [comment]
Yeah, if you are following the paper then finding neighbours for every point takes time, though once you have that HMM runs very fast. Also, you can try improving concurrency in pre-process.py which can make it more faster.

**Comment by r8pto** [comment]
Hi! When I uncommented block 40 to calculate the route distance, I met an Error. Have you ever met that? The Error means that the edges ID is not in the graph (osmox).  
![image](https://github.com/kushagra19/Map_Matching/assets/95324055/c23c8733-a276-47f2-953a-7066af6a6ebb)

**Comment by r8pto** [comment]
Or could you upload your route_distances_FULL file? I'll see how it looks and be able to build it in other ways.

**Comment by kushagra19** [comment]
I do not have the route distance full with me right now, but i faced such errors when osmnx updated their data (edge ids and vertices) but adjacency list still had the old edge ids. When this happens the graph does not have a edge which adjacency list has. Probably investigate whether that edge exists in graph or not.

**Comment by r8pto** [comment]
OK, Thank you again! I will explore this, maybe the downloaded road network from OSM could solve this problem.
